#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := camera_web_server

SOLUTION_PATH ?= $(abspath $(shell pwd))/../../..
IDF_PATH:=/home/xu/Ai-Thinker-Open_ESP32-CAMERA_LAN/esp-idf
include $(SOLUTION_PATH)/components/component_conf.mk
include $(IDF_PATH)/make/project.mk
